apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-monitor
  namespace: todo-lab
  labels:
    release: monitoring  # must match your Prometheus release name
spec:
  selector:
    matchLabels:
      app: api
  namespaceSelector:
    matchNames:
      - todo-lab
  endpoints:
    - port: "http"
      path: /metrics
      interval: 15s
